CONF_THRESHOLD = 0.4
MODEL_PATH = "models/best.pt"
MAX_DISTANCE = 50
MAX_MISSING_FRAME = 5
HISTORY_LENGTH = 15
FPS = 30

# metrics in percentile to be compared with other vehicles 
SPEED_HIGH = 85
ACCEL_HIGH = 90
PATH_RATIO_HIGH = 1.5
THRESHOLD_ANGLE = 25
LOW_DIR_CHANGE = 3
HIGH_DIR_CHANGE = 6 
SPEED_PENALTY = 3
ACC_PENALTY = 4
ERRATIC_PENALTY = 5